# Generated by Django 6.0.4 on 2026-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.IntegerField()),
                ('active_users', models.IntegerField()),
                ('avg_ai_response', models.FloatField()),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
